
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Apr 25 2025 11:53:56 IST (Apr 25 2025 06:23:56 UTC)

// Verification Directory fv/spram16x4_mbist 

module spram16x4_mbist(clk, rst_n, mbist_start, mbist_done, mbist_fail);
  input clk, rst_n, mbist_start;
  output mbist_done, mbist_fail;
  wire clk, rst_n, mbist_start;
  wire mbist_done, mbist_fail;
  wire [3:0] addr;
  wire [3:0] data_in;
  wire [3:0] data_out;
  wire [2:0] state;
  wire csb_n, n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  wire n_7, n_8, n_9, n_10, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17, n_18, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_27, n_28, n_29, n_30;
  wire n_31, n_32, n_33, n_34, n_35, n_36, n_37, n_38;
  wire n_39, n_40, n_41, n_42, n_43, n_44, n_45, n_46;
  wire n_47, n_48, n_49, n_50, n_51, n_52, n_53, n_54;
  wire n_55, n_56, n_57, n_58, n_59, n_60, n_61, n_62;
  wire oe_n, we_n;
  SPRAM_16x4 mem_inst(.CE (clk), .OEB (oe_n), .CSB (csb_n), .WEB
       (we_n), .A (addr), .I ({data_in[0], data_in[0], data_in[0],
       data_in[0]}), .O (data_out));
endmodule

