
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Apr 17 2025 12:05:46 IST (Apr 17 2025 06:35:46 UTC)

// Verification Directory fv/sram_sp_16384d_36w_16m_8b 

module sram_sp_16384d_36w_16m_8b(CLK, CEN, GWEN, A, D, WEN, Q);
  input CLK, CEN, GWEN;
  input [13:0] A;
  input [35:0] D, WEN;
  output [35:0] Q;
  wire CLK, CEN, GWEN;
  wire [13:0] A;
  wire [35:0] D, WEN;
  wire [35:0] Q;
  assign Q[0] = 1'b0;
  assign Q[1] = 1'b0;
  assign Q[2] = 1'b0;
  assign Q[3] = 1'b0;
  assign Q[4] = 1'b0;
  assign Q[5] = 1'b0;
  assign Q[6] = 1'b0;
  assign Q[7] = 1'b0;
  assign Q[8] = 1'b0;
  assign Q[9] = 1'b0;
  assign Q[10] = 1'b0;
  assign Q[11] = 1'b0;
  assign Q[12] = 1'b0;
  assign Q[13] = 1'b0;
  assign Q[14] = 1'b0;
  assign Q[15] = 1'b0;
  assign Q[16] = 1'b0;
  assign Q[17] = 1'b0;
  assign Q[18] = 1'b0;
  assign Q[19] = 1'b0;
  assign Q[20] = 1'b0;
  assign Q[21] = 1'b0;
  assign Q[22] = 1'b0;
  assign Q[23] = 1'b0;
  assign Q[24] = 1'b0;
  assign Q[25] = 1'b0;
  assign Q[26] = 1'b0;
  assign Q[27] = 1'b0;
  assign Q[28] = 1'b0;
  assign Q[29] = 1'b0;
  assign Q[30] = 1'b0;
  assign Q[31] = 1'b0;
  assign Q[32] = 1'b0;
  assign Q[33] = 1'b0;
  assign Q[34] = 1'b0;
  assign Q[35] = 1'b0;
endmodule

